name: Enhanced Letterboxd Data Scraping

on:
  schedule:
    - cron: '0 8 * * *'  # Daily at 8 AM UTC
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r scraper/requirements.txt
        
    - name: Run enhanced scraper
      env:
        LETTERBOXD_USERNAME: ${{ secrets.LETTERBOXD_USERNAME }}
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      run: |
        cd scraper
        python enhanced_scraper.py
        
    - name: Move data files to correct location
      run: |
        mkdir -p data
        if [ -f scraper/data/movies.csv ]; then
          mv scraper/data/movies.csv data/
        fi
        if [ -f scraper/data/stats.json ]; then
          mv scraper/data/stats.json data/
        fi
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update Letterboxd data with enhanced scraper - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        fi
