name: Update Letterboxd Data

on:
  schedule:
    # Run daily at 1:00 UTC (6:30 AM IST)
    - cron: '0 1 * * *'
  workflow_dispatch:  # Allow manual runs

jobs:
  scrape:
    runs-on: ubuntu-latest

    permissions:
      contents: write     
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd scraper
        pip install -r requirements.txt

    - name: Run scraper
      env:
        LETTERBOXD_USERNAME: ${{ secrets.LETTERBOXD_USERNAME }}
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      run: |
        cd scraper
        python scrape_letterboxd.py

    - name: Move generated data into place
      run: |
        mkdir -p data
        if [ -f scraper/data/movies.csv ]; then
          mv scraper/data/movies.csv data/
        fi
        if [ -f scraper/data/stats.json ]; then
          mv scraper/data/stats.json data/
        fi

    - name: Resolve any rebase conflicts in stats.json
      run: |
        # If during a rebase conflict, accept the incoming stats.json update
        if grep -q '^<<<<<<<' data/stats.json; then
          git add data/stats.json
          git rebase --continue || echo "No rebase in progress"
        fi

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git diff --staged --quiet || (git commit -m "🎬 Update movie data - $(date)" && git push)
